// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Index() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div><div style=\"display: flex; justify-content: space-between; align-items: center;\"><h1 style=\"cursor: pointer;\" hx-on::click=\"window.location.href=&#39;/&#39;;\">ITCHGREP</h1><div style=\"text-align: right;\"><!-- Right-aligned project description --><p style=\"font-size: 1.6rem; margin: 0;\">search itch.io/game-assets by text instead of just tags.</p><p style=\"font-size: 1.6rem; margin: 0;\">created by <a href=\"#\">winterveil</a>.</p><p style=\"font-size: 1.6rem; margin: 0; text-align: left; margin-top: -0.4rem;\"><a href=\"#\">CONTACT</a> <a href=\"#\">ABOUT</a> <a href=\"\">GITHUB</a></p></div></div><form hx-post=\"/query/1\" hx-target=\"#asset-list\" hx-swap=\"innerHTML\" style=\"display: flex; align-items: center;\"><input id=\"query-input\" type=\"text\" name=\"query\" placeholder=\"bones...\" required style=\"flex-grow: 1; margin-right: 8px; width: auto;\"> <button type=\"submit\" style=\"line-height: 1.2; margin-bottom: 1.6rem\">SEARCH</button></form><div id=\"asset-list\"><div hx-get=\"/assets/1\" hx-trigger=\"load\" hx-swap=\"outerHTML\" hx-target=\"this\"></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
